### ISSUE TITLE
Not able to run the simulations

### ISSUE THREAD

**Issue by AWehenkel** [alemelis/openBF-db#1]
Hi,

I did not find how I could run openBF on the generated config files. It seems that OpenBF expect a yml config file and an inlet file. 
Shall I just translate the jl and css file into a corresponding yml config file and run openBF on it?

Also, I wonder what run_simulations.jl you are referring to in the README.md. Shall I replace it with a file that call the run_simulations function from openBF?

Thanks a lot in advance for your help!

Best regards,

Antoine

**Comment by alemelis** [comment]
hi @AWehenkel 

I'm afraid that the correct way of running this repository is lost. The main aim of this was to hold the heroku app which you can use going on
https://obfdb.herokuapp.com/obfdb

better refer to [openBF repository](https://github.com/INSIGNEO/openBF) in case you want to run simulations

we're in the process of rewriting the documentation and updating the config files. In the meantime, please let me know if I can help you further

**Comment by alemelis** [comment]
@AWehenkel 
I did some digging in my notes (this repository is 5 years old after all!) and I can confirm that:
- you should translate the csv to yaml
- the inlet data is in the `_inlet.dat` file in the root of this repo
- `run_simulation.jl` is a legacy script I can't find (will do some more digging) but iirc it should be the same of running `openBF.runSimulation("your_config_file.yml", verbose=true, conv_ceil=true)`

hope this helps

**Comment by AWehenkel** [comment]
Hi @alemelis,

Thanks for your answer! I managed to run a simulation by compiling the old files into the config files expected by the last version of OpenBF.
I can share my code in case you want, it is just few lines but it might save to someone else in the future!

Cheers,

Antoine

**Comment by alemelis** [comment]
@AWehenkel glad it works!

yes, that would be a valuable contribution
Would you mind opening a PR on this repository?
